# Generated by Django 4.0.1 on 2022-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo1', models.ImageField(blank=True, upload_to='', verbose_name='Фото1')),
                ('photo2', models.ImageField(blank=True, upload_to='', verbose_name='Фото2')),
                ('photo3', models.ImageField(blank=True, upload_to='', verbose_name='Фото3')),
                ('photo4', models.ImageField(blank=True, upload_to='', verbose_name='Фото4')),
                ('photo5', models.ImageField(blank=True, upload_to='', verbose_name='Фото5')),
                ('price', models.TextField(max_length=11, verbose_name='Цена')),
            ],
        ),
    ]
