# Generated by Django 4.0.1 on 2022-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='main/img', verbose_name='Фото1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='main/img', verbose_name='Фото2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='main/img', verbose_name='Фото3'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='main/img', verbose_name='Фото4'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='main/img', verbose_name='Фото5'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Цена'),
        ),
    ]
